### ISSUE TITLE
makelogs-3.0.2 creates single logstash-0 index

### ISSUE THREAD

**Issue by ycombinator** [elastic/makelogs#25]
I believe previous versions of makelogs (2.x) created 3 time-based indices. Is this a regression in makelogs 3.x?

**Comment by spalger** [comment]
It's actually intended. Indices are now created based on a 0-based counter, and roll over to a new index based on the `--index-interval`. The intention is to use the new `field_stats` resolution in kibana, and prevent creating extra work for kibana when only 10k documents are created over the course of a month. If you'd like to have more indices, I suggest lowering the `--index-interval` and raising the `--count` to get the desired effect.

**Comment by ycombinator** [comment]
Thanks for the explanation, @spalger!
