### ISSUE TITLE
Deprecate old published makelogs on npm

### ISSUE THREAD

**Issue by markov00** [elastic/makelogs#46]
On NPM we have now the `@elastic/makelogs` and the previous `makelogs` with the last update to 4.3.0.
Could we in a way deprecate the `makelogs` published library and redirect to `@elastic/makelogs` for new updates?

**Comment by spalger** [comment]
Done 

![image](https://user-images.githubusercontent.com/1329312/55092296-8eddc000-506f-11e9-8912-3b485ec0b41e.png)
